# ~/.config/starship.toml

"$schema" = 'https://starship.rs/config-schema.json'

format = "$all"

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 4

[package]
disabled = true

[cmd_duration]
disabled = false

[battery]
disabled = false
full_symbol = "ğŸ”‹ "
discharging_symbol = "ğŸª« "
charging_symbol = "âš¡ï¸ "
empty_symbol = "ğŸ’€ "

[[battery.display]]
threshold = 10
style = "bold red"
discharging_symbol = "ğŸª«"

[[battery.display]]
threshold = 30
style = "bold yellow"
discharging_symbol = "ğŸª« "

[time]
disabled = false

[ruby]
disabled = true

[aws]
disabled = false
format = "on [$profile](bold yellow)"

[hostname]
disabled = false
format = "[$hostname](bold dimmed white) "
ssh_only = false

